### ISSUE TITLE
Issue on Appveyor

### ISSUE THREAD

**Issue by Alexander-Barth** [helgee/RemoteFiles.jl#11]
Firstly, many thanks for this great package. It is really nice how one can efficiently access remote dataset with RemoteFiles.jl.

I try to use it in a package, where I download some file:

https://github.com/Alexander-Barth/APTDecoder.jl/blob/938682ef3383b9c4fea1eb798225a9f1b31e6c0a/src/georef.jl#L59

I works perfectly, on my local linux and windows machine. However, on appveyor (with windows OS), I have some problems:

https://ci.appveyor.com/project/Alexander-Barth/aptdecoder-jl/builds/26959260/job/hpqui2i3nktcd0pa#L321

It seems that the file get downloaded several times. Also a remote file, final results in a  "403 Forbidden" error. Maybe because of too many unsuccessfully attempts. 

I am wondering if you have some idea what is going on. I see this issue only on appveyor; travis CI on Linux and MacOS works fine.

**Comment by Alexander-Barth** [comment]
The server seem to require an `User-Agent` and `Accept` HTTP header. Also on Linux is this behaviour:

```
r = HTTP.get("https://datacenter.iers.org/data/latestVersion/223_EOP_C04_14.62-NOW.IAU1980223.txt");
ERROR: HTTP.ExceptionRequest.StatusError(403, "GET", "/data/latestVersion/223_EOP_C04_14.62-NOW.IAU1980223.txt", HTTP.Messages.Response:
"""
HTTP/1.1 403 Forbidden
Date: Mon, 26 Aug 2019 20:45:38 GMT
Server: Apache
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000;includeSubDomains;preload
Content-Length: 257
Connection: close
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /data/latestVersion/223_EOP_C04_14.62-NOW.IAU1980223.txt
on this server.</p>
</body></html>
""")
Stacktrace:
 [1] #request#1(::Base.Iterators.Pairs{Symbol,Nothing,Tuple{Symbol},NamedTuple{(:iofunction,),Tuple{Nothing}}}, ::typeof(HTTP.request), ::Type{HTTP.ExceptionRequest.ExceptionLayer{HTTP.ConnectionRequest.ConnectionPoolLayer{HTTP.StreamRequest.StreamLayer}}}, ::HTTP.URIs.URI, ::Vararg{Any,N} where N) at /home/abarth/.julia/packages/HTTP/wY7Vc/src/ExceptionRequest.jl:22
```

While the following works:
```
r = HTTP.get("https://datacenter.iers.org/data/latestVersion/223_EOP_C04_14.62-NOW.IAU1980223.txt",["User-Agent" => "non-empty","Accept" => "*/*"]);
```

As far as I can tell, I can set the user agent as `HTTP.MessageRequest.setuseragent!("APTDecoder")`, but I still need to set the `Accept` header.

**Comment by helgee** [comment]
Thanks for the debugging!

I recently made the detection of cURL on Windows dependent on the Windows version, which was a silly idea in retrospect. So the obvious issue is that cURL should be used on AV and not the fallback on HTTP.jl. Nevertheless, it should still work with HTTP.jl.

Do you think it would be appropriate to set these headers globally in RemoteFiles.jl?

**Comment by helgee** [comment]
> Firstly, many thanks for this great package. It is really nice how one can efficiently access remote dataset with RemoteFiles.jl.

And thank you 😄

**Comment by helgee** [comment]
I think I fixed the cURL issue and added the required headers: https://github.com/helgee/RemoteFiles.jl/commit/72e8566ad12734ac50e95d1f4a6a209774ae87b0

I will tag a new version as soon as CI passes.

**Comment by Alexander-Barth** [comment]
This is great! Thank you so much for you quick response and fix. I indeed think that it is acceptable to set these headers globally because also the `curl` and  `wget` command also set `User-Agent` and `Accept` headers similarly.

```
 curl --verbose https://datacenter.iers.org/data/latestVersion/223_EOP_C04_14.62-NOW.IAU1980223.txt > /dev/null
[...]
> GET /data/latestVersion/223_EOP_C04_14.62-NOW.IAU1980223.txt HTTP/1.1
> Host: datacenter.iers.org
> User-Agent: curl/7.58.0
> Accept: */*
[...]

```

```
 wget -d https://datacenter.iers.org/data/latestVersion/223_EOP_C04_14.62-NOW.IAU1980223.txt 
GET /data/latestVersion/223_EOP_C04_14.62-NOW.IAU1980223.txt HTTP/1.1
User-Agent: Wget/1.19.4 (linux-gnu)
Accept: */*
Accept-Encoding: identity
Host: datacenter.iers.org
Connection: Keep-Alive
[...]
```

Thanks a lot!
