### ISSUE TITLE
Is the macro interface needed?

### ISSUE THREAD

**Issue by mauro3** [helgee/RemoteFiles.jl#14]
The macro expansion of `@RemoteFile` is
```julia
julia> @macroexpand  @RemoteFile(somename, "file://~/myfile.txt", file="localname.txt")
:(somename = RemoteFiles.RemoteFile("file://~/myfile.txt"; file = "localname.txt", dir = "..."))
```
arguably just using
```julia
somename = RemoteFile("file://~/myfile.txt"; file = "localname.txt")
```
would be clearer? (There is the issue of `__source__` but that would be solved by dropping that, x-ref: #13)

Similarly for `@RemoteFileSet`, why not just
```julia
rfs = RemoteFileSet("Some description",
  set1 = RemoteFile("file://~/myfile.txt"; file = "localname.txt"),
  set2 = RemoteFile("file://~/myfile.txt"; file = "localname.txt")
  )
```

**Comment by helgee** [comment]
I believe getting the source location was the only reason for using macros but I do not really remember.

This would work:
```julia
rfs = RemoteFileSet(
    "Some description",
    set1 => RemoteFile("file://~/myfile.txt"; file = "localname.txt"),
    set2 => RemoteFile("file://~/myfile.txt"; file = "localname.txt"),
)
```

**Comment by mauro3** [comment]
The version i posted (using `=` not `=>`) actually works.  As I'm not using the automatic "source", I just use the non-macro version.  Maybe worth to add that to the docs?
