### ISSUE TITLE
File data is not updated in macOS

### ISSUE THREAD

**Issue by ronisbr** [helgee/RemoteFiles.jl#21]
Hi @helgee !

I am having a problem with RemoteFiles in macOS.

I am asking to download the IERS file:

```julia
julia> using SatelliteToolbox

julia> get_iers_eop()
[ Info: Downloading file 'EOP_IAU1980.TXT' from 'https://datacenter.iers.org/data/latestVersion/223_EOP_C04_14.62-NOW.IAU1980223.txt' with cURL.
```

Then, inside SatelliteToolbox.jl I can see it:

```bash
-rw-r--r--   1 ronan  staff  3377677  7 Mai 18:25 EOP_IAU1980.TXT
```

One day after, I ask to download it again. It downloads but the timestamp does not change. Hence, it will always download it when I call that funciton.

If I remove the file and download it again, then it works:

```bash
-rw-r--r--   1 ronan staff  3377677  8 Mai 12:03 EOP_IAU1980.TXT
```

Is it expected?

I am defining the remote file as follows:

```julia
    _eop_iau1980 = @RemoteFile(@eval($url),
                               file="EOP_IAU1980.TXT",
                               updates=:daily)
    download(_eop_iau1980; force = force_download)
```

**Comment by ronisbr** [comment]
I think I understood. The file has not changed. Thus, it does not update the file inside the `data` directory:

```julia
[ Info: File 'EOP_IAU1980.TXT' has not changed. Update skipped.
```

Is there a way to force it always update the file when it downloads it?

Notice that `force` does not help, because it also forces to download the file again. I want something like that: if the file was downloaded and has no update, update the current file to change the timestamp.

**Comment by helgee** [comment]
Registration PR is underway: https://github.com/JuliaRegistries/General/pull/36333
