### ISSUE TITLE
Change behavior of weekly update

### ISSUE THREAD

**Issue by ronisbr** [helgee/RemoteFiles.jl#25]
Hi @helgee !

Currently, the weekly update is equal to the Monday update. Can we change this behavior to something like this: download the file again if the file date is 7 days older than the current date?

**Comment by helgee** [comment]
Sure 👍 Wanna make a PR?

**Comment by ronisbr** [comment]
Sure! Thanks :)

**Comment by ronisbr** [comment]
By the way @helgee , I think we have a problem of time zone here.

The function `isoutdated` compares `now()` with `unix2datetime`. The former returns the date considering the time zone locale whereas the latter returns UTC. Maybe the correct approach is to use always `now(UTC)`. However, in this case, all the definitions (Monday, Tuesday, etc.) will be with respect to UTC instead of the local time. What do you think?

**Comment by ronisbr** [comment]
I am also wondering if we can use this PR to also change the behavior of `:daily`, `:monthly`, and `:yearly`. For example, using `:monthly`, the problem is that if a file is uploaded at March 30, then RemoteFiles will download it every time until a new version is released in April 30. I think it makes more sense if those intervals are related to the current file date instead of the beginning of the month / week / day.

I will create a PR and we can discuss on top of that.

**Comment by ronisbr** [comment]
Thanks @helgee !

Is it possible to release a new version with this modification?
