### ISSUE TITLE
Implement load

### ISSUE THREAD

**Issue by femtotrader** [helgee/RemoteFiles.jl#3]
Hello,

Following https://github.com/davidanthoff/Queryverse.jl/issues/6#issuecomment-406312750
`load` function (calling `FileIO.load`) should be implemented

```julia
import FileIO: load

"""
    load(rf::RemoteFile)

Loads the contents of a remote file, downloading file if
it haven't been done previously, reading file from disk
and trying to infer the format from filename and/or magic 
bytes in the file.
"""
function load(rf::RemoteFile)
    if !isfile(rf)
        download(rf)
    end
    load(path(rf))
end
```

Kind regards

**Comment by helgee** [comment]
Makes sense 👍 Will do...

**Comment by helgee** [comment]
Well, that took a while. Sorry 😬

**Comment by femtotrader** [comment]
Thanks @helgee 
Could you publish a new release with this feature?

**Comment by helgee** [comment]
Under way: https://github.com/JuliaRegistries/General/pull/2346
